/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TopLevelEntry = BibliographyEntry & {
  type: EntryType1;
  [k: string]: unknown;
};
/**
 * The media type of the entry. Often determines the structure of references.
 * Entry types are case-insensitive in Typst (first letter can be upper or lowercase).
 */
export type EntryType = string;
/**
 * The title of this entry.
 */
export type Title =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
export type Value = string;
/**
 * If true, disables text case transformations. Preserves casing as it appears in source.
 */
export type Verbatim = boolean;
/**
 * A short form that a citation style can choose to render over the longer form.
 */
export type ShortForm = string;
/**
 * The person or people primarily responsible for the creation of this entry.
 */
export type Author = Person | [Person, ...Person[]];
/**
 * A person with a name and optionally given name, prefix, suffix, and alias.
 * String format: "Last, First" or "Prefix Last, First, Suffix"
 * Prefix is auto-detected using BibTeX algorithm (consecutive lowercase words at start).
 */
export type Person =
  | string
  | {
      name: FamilyName;
      "given-name"?: GivenName;
      prefix?: NamePrefix;
      suffix?: NameSuffix;
      alias?: Alias;
    };
/**
 * The family/last name of the person (required).
 */
export type FamilyName = string;
/**
 * The given/first name of the person.
 */
export type GivenName = string;
/**
 * The prefix of the person's name (e.g., "von", "van der").
 */
export type NamePrefix = string;
/**
 * The suffix of the person's name (e.g., "Jr.", "III").
 */
export type NameSuffix = string;
/**
 * An alternative name or pseudonym for the person.
 */
export type Alias = string;
/**
 * The date of publication or creation of this entry.
 */
export type Date = number | string;
/**
 * Entry in which the current entry was published, or to which it is strongly associated.
 */
export type ParentEntry = BibliographyEntry | [BibliographyEntry, ...BibliographyEntry[]];
/**
 * The abstract or summary of the entry.
 */
export type Abstract =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * The type, class, or subtype of the item (e.g. "Doctoral dissertation" for a PhD thesis; "NIH Publication" for an NIH technical report).
 * Do not use for topical descriptions or categories (e.g. "adventure" for an adventure movie).
 */
export type Genre =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * The person or people responsible for selecting and revising the content of the entry.
 */
export type Editor = Person | [Person, ...Person[]];
/**
 * People involved with the entry that do not fit `author` or `editor` roles.
 *
 * @minItems 1
 */
export type AffiliatedPeople = [AffiliatedRole, ...AffiliatedRole[]];
/**
 * The role of the person or people in relation to the entry.
 */
export type Role =
  | "translator"
  | "afterword"
  | "foreword"
  | "introduction"
  | "annotator"
  | "commentator"
  | "holder"
  | "compiler"
  | "founder"
  | "collaborator"
  | "organizer"
  | "cast-member"
  | "composer"
  | "producer"
  | "executive-producer"
  | "writer"
  | "cinematography"
  | "director"
  | "illustrator"
  | "narrator";
/**
 * The name(s) of the person or people involved in the role.
 */
export type PeopleInvolved = Person | [Person, ...Person[]];
/**
 * The number of the item in a library, institution, or collection. Use with the `archive` field.
 */
export type CallNumber =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * The publisher of the item. Can include name and location.
 */
export type Publisher =
  | string
  | {
      name: PublisherName;
      location?: PublisherLocation;
    };
/**
 * The name of the publisher.
 */
export type PublisherName = string;
/**
 * The location of the publisher.
 */
export type PublisherLocation = string;
/**
 * The location at which the entry is physically located or took place.
 * For the location where an item was published, use the `publisher` field instead.
 */
export type Location =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * The organization at/for which the entry was produced.
 */
export type Organization =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * For an entry whose parent has multiple issues, this field identifies to which specific issue the entry belongs.
 * Also used to indicate the episode number for TV series.
 */
export type Issue = number | string;
/**
 * For an entry whose parent has multiple volumes, parts, seasons, etc., this field identifies to which specific volume the entry belongs.
 */
export type Volume = number | string;
/**
 * The total number of volumes, parts, seasons, etc., in the series that contains this entry.
 */
export type VolumeTotal = number;
/**
 * The number of the chapter in the referenced work where this item can be found.
 * When the chapter itself is the item being cited (common if it has its own non-numeric title),
 * prefer using `type: chapter` for the entry while specifying the containing work's data as its parent.
 */
export type Chapter = number | string;
/**
 * The published version of the entry.
 */
export type Edition = number | string;
/**
 * The range of pages within the parent that this entry occupies.
 */
export type PageRange = number | string;
/**
 * The total number of pages in the entry.
 */
export type PageTotal = number;
/**
 * The time range within the parent at which this entry starts and ends.
 */
export type TimeRange = string;
/**
 * The total runtime of the entry.
 */
export type Runtime = string;
/**
 * The canonical public URL of the entry, which may include an access date.
 */
export type URL =
  | string
  | {
      value: URLValue;
      date?: AccessDate;
    };
/**
 * The URL value.
 */
export type URLValue = string;
/**
 * The date when the URL was accessed.
 */
export type AccessDate = number | string;
/**
 * Any serial number, including article numbers, associated with the entry.
 * If you have serial numbers of well-known schemes like `doi`, you should put them into the serial number as a dictionary.
 * Hayagriva will recognize and specially treat `doi`, `isbn`, `issn`, `pmid`, `pmcid`, and `arxiv`.
 * You can also include `serial` for the serial number when you provide other formats as well.
 */
export type SerialNumber =
  | string
  | number
  | {
      doi?: DOI;
      isbn?: ISBN;
      issn?: ISSN;
      pmid?: PMID;
      pmcid?: PMCID;
      arxiv?: ArXiv;
      serial?: SerialNumber1;
      [k: string]: string;
    };
/**
 * Digital Object Identifier.
 */
export type DOI = string;
/**
 * International Standard Book Number.
 */
export type ISBN = string;
/**
 * International Standard Serial Number.
 */
export type ISSN = string;
/**
 * PubMed Identifier.
 */
export type PMID = string;
/**
 * PubMed Central Identifier.
 */
export type PMCID = string;
/**
 * arXiv Identifier.
 */
export type ArXiv = string;
/**
 * Generic serial number.
 */
export type SerialNumber1 = string;
/**
 * The language of the entry as a Unicode Language Identifier.
 */
export type Language = string;
/**
 * The name of the institution/collection where the entry is kept.
 */
export type Archive =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * The location of the institution/collection where the entry is kept.
 */
export type ArchiveLocation =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * A short markup, decoration, or annotation to the entry (e.g., to indicate items included in a review).
 */
export type Note =
  | string
  | {
      value: Value;
      verbatim?: Verbatim;
      short?: ShortForm;
    };
/**
 * The media type of the entry. Often determines the structure of references.
 * Entry types are case-insensitive in Typst (first letter can be upper or lowercase).
 */
export type EntryType1 = string;

/**
 * Schema for Hayagriva YAML bibliography files, a bibliography management format for the modern age.
 * https://github.com/typst/hayagriva/blob/main/docs/file-format.md
 */
export interface HayagrivaBibliographyFormat {
  [k: string]: TopLevelEntry;
}
/**
 * A single bibliography entry with fields describing a work.
 */
export interface BibliographyEntry {
  type?: EntryType;
  title?: Title;
  author?: Author;
  date?: Date;
  parent?: ParentEntry;
  abstract?: Abstract;
  genre?: Genre;
  editor?: Editor;
  affiliated?: AffiliatedPeople;
  "call-number"?: CallNumber;
  publisher?: Publisher;
  location?: Location;
  organization?: Organization;
  issue?: Issue;
  volume?: Volume;
  "volume-total"?: VolumeTotal;
  chapter?: Chapter;
  edition?: Edition;
  "page-range"?: PageRange;
  "page-total"?: PageTotal;
  "time-range"?: TimeRange;
  runtime?: Runtime;
  url?: URL;
  "serial-number"?: SerialNumber;
  language?: Language;
  archive?: Archive;
  "archive-location"?: ArchiveLocation;
  note?: Note;
}
export interface AffiliatedRole {
  role: Role;
  names: PeopleInvolved;
}
